---
default_install_hook_types:
  - pre-commit
  - commit-msg

fail_fast: false
minimum_pre_commit_version: '4.6.0'
repos:
  - repo: local
    hooks:
      - id: prettier check
        name: Prettier check
        entry: mise format:check
        language: system
        files: ^site/src
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        name: Actionlint

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.28.0
    hooks:
      - id: zizmor
        name: Zizmor pre-commit

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        name: Check commit message for conventional commits format
        stages: [ commit-msg ]
        args: [ --strict, --force-scope, feat, chore, docs, test ]
