[tools]
node = "24"
python = "3"

[env]
_.python.venv = ".venv"

[tasks.run]
dir = "./site"
run = "npm run dev"

[tasks."format:check"]
dir = "./site"
run = "npm run format:check"

[tasks."format:write"]
dir = "./site"
run = "npm run format:write"

[tasks."cypress:run"]
dir = "./site"
run = "npm run cypress:run"

[tasks.install]
dir = "./site"
run = "npm install"