name: Cypress E2E

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: 24

      - name: Cypress run
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@948d67d3074f1bbb6379c8bdbb04e95d2f8e593f # 7.4.0
        with:
          working-directory: ./site
          config: video=false
          install-command: npm ci
          build: npm run build
          start: npm run preview
          wait-on: 'http://localhost:4321'
          wait-on-timeout: 60

