name: Cypress E2E

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  cypress-run:
    defaults:
      run:
        working-directory: ./site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          working-directory: ./site
          config: video=false
          build: npm run build
          start: npm run preview
          wait-on: 'http://localhost:4321'
          wait-on-timeout: 60
