name: verify-dco

on:
  pull_request:
    branches:
      - main

jobs:
  verify-dco:
    name: Verify Developer Certificate of Origin (DCO)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Run Verify Developer Certificate of Origin (DCO)
        # https://github.com/tisonkun/actions-dco
        uses: tisonkun/actions-dco@v1.1
